### ISSUE TITLE
windsor 5.1.2 Lifestyle Prewebrequest

### ISSUE THREAD

**Issue by gurbeers** [castleproject/Windsor#640] opened 2022-11-22 02:20 UTC
Hello Team, i recently upgrade by project from VS2013 4.0 to VS2022 4.8 
We updated Entity Framework 4.4 to 6 
Castle core 3.1 to 5.1.0
Castle windsor 3.1 to  5.1.1
In old version we used 
container.register(component.for<IApprovals>.Implementedby<CPRAutomation.domain.concrete.MLIB.Approvals>().Lifestyle.Prewebrequest.Named("ApprovalMappper")));
In new i converted into 
container.register(component.for<IApprovals>.Implementedby<CPRAutomation.domain.concrete.MLIB.Approvals>().Lifestyle.Singleton.Named("ApprovalMappper")));

Similar way in old 
container.register(component.for<IFacilitytypes>.Implementedby<CPRAutomation.domain.concrete.MLIB.Facilitytypes>().Lifestyle.Prewebrequest);
container.register(component.for<IFacilitytypes>.Implementedby<CPRAutomation.domain.concrete.MLIB.Facilitytypes>().Lifestylesingleton());

I am not sure this conversion is correct or not but I loosing data, specially for Approval Table 

I dont know what is wrong also I am unble to find ApprovalMappper - I dont see any config where it is defined.

please suggest if i am doing anything wrong.

**Comment by ikkentim** [comment] 2022-11-23 08:43
Castle.Windsor is not currently compatible with Castle.Core 5.x.

**Comment by renemadsen** [comment] 2022-11-29 10:11
> Castle.Windsor is not currently compatible with Castle.Core 5.x.

When do we expect that to happen?

**Comment by jeme** [comment] 2022-11-29 11:16
sort of duplicate of: 623 right?

**Comment by jonorossi** [comment] 2022-11-30 00:24
> Castle core 3.1 to 5.1.0
> Castle windsor 3.1 to 5.1.1

Did you read the changelog for 5.0.0? Listed under `5.0.0-beta001` there is a breaking change for System.Web support.

Why not Windsor 5.1.2, it prevents problems with not supporting Castle Core 5.x?

> container.register(component.for.Implementedby<CPRAutomation.domain.concrete.MLIB.Approvals>().Lifestyle.Prewebrequest.Named("ApprovalMappper")));
> In new i converted into
> container.register(component.for.Implementedby<CPRAutomation.domain.concrete.MLIB.Approvals>().Lifestyle.Singleton.Named("ApprovalMappper")));

Why did you change from per web request to singleton? See the [docs](https://github.com/castleproject/Windsor/blob/master/docs/systemweb-facility.md) for using `LifestylePerWebRequest`.

> I dont know what is wrong also I am unble to find ApprovalMappper - I dont see any config where it is defined.

`ApprovalMappper` isn't a Windsor thing, that's your application.

**Closed by jonorossi** 2022-11-30 00:24 UTC
