### ISSUE TITLE
Castle Windsor 3.3 XML config file component parsing error

### ISSUE THREAD

**Issue by ChrisM99** [castleproject/Windsor#76] opened 2015-01-15 09:04 UTC
I'm in the process of upgrading our Castle Windsor dlls from v2.1 to 3.3. 
We have to use the app.config to define our components due to our installation \configuration requirements.

Since upgrading to 3.3, when I try to resolve the dependencies, I get the following error:

Castle.MicroKernel.Resolvers.DependencyResolverException : 
Could not convert parameter 'myProcessor' to type 'ImyProcessor'.  
----> Castle.MicroKernel.SubSystems.Conversion.ConverterException : 
Could not convert expression '${myProcessor}		
' to type 'Interfaces.ImyProcessor'. 
Expecting a reference override like ${some key}

This appears to be caused by a change in the way the component sections of the config file are parsed in the latest version.

Our component parameters are formatted like this (i.e. split onto multiple lines)

```
<parameters>
    <myProcessor>
       ${myProcessor}
    </myProcessor>
</parameters>```

It only works if I change them to a single line like this:

```<parameters>
   <myProcessor>${myProcessor}</myProcessor>
</parameters>```


Is there likely to be a fix for this as reformatting all of our config files for our clients as well as updating our documentation will be considerable work.



Thanks


Chris

**Comment by boznet** [comment] 2015-01-15 14:26
Here is a failing test (add to ConfigurationTestCase)
I have added line breaks around ${Proxy} to reproduce the error

```
[Test]
		[Bug("GitHub-76")]
		public void ShouldNotThrowDependencyResolverException()
		{
			const string config = @"
<configuration>
    <facilities>
    </facilities>
    <components>
        <component id='MyClass'
            service='IEmptyService'
            type='EmptyServiceA'/>
        <component id='Proxy'
            service='IEmptyService'
            type='EmptyServiceDecorator'>
            <parameters>
                <other>${MyClass}</other>
            </parameters>
        </component>
        <component id='ClassUser'
            type='UsesIEmptyService'>
            <parameters>
                <emptyService>
					${Proxy}
				</emptyService>
            </parameters>
        </component>
    </components>
</configuration>";

			Container.Install(Configuration.FromXml(new StaticContentResource(config)));

			Assert.DoesNotThrow( () =>Container.Resolve<UsesIEmptyService>());

		}
```

**Comment by ChrisM99** [comment] 2015-01-15 14:58
It looks as though the fix to add this Trim() to the DefaultTextNodeProcessor.cs
This removes any carriage returns and tabs etc

```
public override void Process(IXmlProcessorNodeList nodeList, IXmlProcessorEngine engine)
		{
			var node = nodeList.Current as XmlCharacterData;
			node.Value = node.Value.Trim();

			ProcessString(node, node.Value, engine);
		}
```

**Comment by kkozmic** [comment] 2015-06-12 06:12
Would you like to create a pull request for that @ChrisM99 ?

**Comment by jonorossi** [comment] 2015-06-12 06:14
@ChrisM99 already submitted #77.

**Comment by kkozmic** [comment] 2015-06-12 06:18
Thanks @jonorossi 

I missed that, since there was no link to the PR from this issue (I just added it). In that case I think we can close the issue and carry on in the PR

**Closed by kkozmic** 2015-06-12 06:18 UTC
