### ISSUE TITLE
Singleton lifestyle not works when using DynamicParameters

### ISSUE THREAD

**Issue by VitalickS** [castleproject/Windsor#73] opened 2014-12-13 15:49 UTC
I Register my component with Singleton lifestyle. But when I change constructor initialization from simple to DynamicParameters, it resolves always new instance.

**Comment by kkozmic** [comment] 2015-06-12 06:25
Since this hasn't been answered I'm closing this issue. @VitalickS if you have a working reproduction please submit it as a separate issue, or better yet, a pull request

**Closed by kkozmic** 2015-06-12 06:25 UTC
