### ISSUE TITLE
Castle.Windsor.Extensions.DependencyInjection: Transient services are not disposed.

### ISSUE THREAD

**Issue by AntonioDrusin** [castleproject/Windsor#530] opened 2020-06-17 17:08 UTC
- Have a controller dependent on a transient service.
```
Component.For<ITransientService>().ImplementedBy<TransientService>().LifestyleTransient(),
```
or with MSInjection
```
services.AddTransient<ITransientService, TransientService>();
```
- When using MS injection the service is disposed right after the controller is disposed.
- When using Windsor the service is disposed after application shutdown.

Project to test out this scenario: https://github.com/AntonioDrusin/WindsorNetCore31Tester

It is inconsistent that the behavior of transient services is different between using MSInjection and CastleWindsor.
The behavior is also inconsistent with how Transient services work in Windsor.

The planned use for this extension is to be able to use our current windsor registrations in Net Core 3.0. With this difference in behavior (transient services not being freeed until shutdown) that won't be possible.

**Comment by nativenolde** [comment] 2020-06-25 07:05
@ltines i can confirm the issue as reported by @AntonioDrusin

**Comment by stylefish** [comment] 2020-06-26 12:07
i'm facing the same issue
and thansk for the great work on the integration with MS DI, highly appreciated :)

**Comment by ltines** [comment] 2020-06-27 10:29
Hi @AntonioDrusin ,

this is due to different semantics of "transient" between Castle and MS DI. I tried to keep it based on where you register the component:
* if you register it via `Component.For<ITransientService>().ImplementedBy<TransientService>().LifestyleTransient(),` it will follow Windsor semantics and you are responsible for releasing and destroying the instance
* if you register it via ServiceCollection it will follow .NET semantics and ties the instance to the ServiceProvider / ServiceScope. The instance will be released on disposing the scope. This is required by .NET

Though if you wanna register it with Windsor directly but you want the lifecycle to follow .NET you can do this
```
Component.For<ITransientService>().ImplementedBy<TransientService>().LifestyleNetTransient()
```

**Comment by AntonioDrusin** [comment] 2020-06-29 17:54
@ltines Thank You for working on this.

I do not understand very well the concept of different semantics of transient. When I register a transient service in castle windsor (outside of the Microsoft DI framework), I always observed the service being released as soon as the class dependent on it was released. if A depends on B and A is released, then B is released as well.

**Comment by nativenolde** [comment] 2020-07-13 08:34
> I do not understand very well the concept of different semantics of transient. When I register a transient service in castle windsor (outside of the Microsoft DI framework), I always observed the service being released as soon as the class dependent on it was released. if A depends on B and A is released, then B is released as well.

That's also my understanding of a transient lifestyle and probably that of most developers out there.

If windsor should be used as implementation of microsoft extensions dependency injection, it has to adopt the imposed principles, at least in my opinion. To have a separate "net-transient" lifestyle could be confusing and should be avoided.

**Comment by nativenolde** [comment] 2020-07-23 10:56
I guess everyone who's using windsor with asp dotnet core appreciates your efforts on the ms-ex-di implementation and the windsor project itself, so let me address a big thank you here.

In order to achieve a consensus we should try to move this into a more meaningful conversation, as it has a big impact on how things are going to work in windsor.

@ltines any thoughts on this?

**Comment by AntonioDrusin** [comment] 2020-08-09 13:03
With Castle Windsor
```
 public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(
                Component.For<ITransientService>().ImplementedBy<TransientService>().LifestyleTransient()         
            );
        }
    }
```
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\dev\Windsor\WindsorNetCore31Tester\WebApplication3
TransientService 1 created
Controller created
Controller disposed
TransientService 2 created
Controller created
Controller disposed
```

With MS Injection
```
 public static void MsInstall(IServiceCollection services)
        {
            services.AddScoped<IPerWebRequestService, PerWebRequestService>();
        }
```
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\dev\Windsor\WindsorNetCore31Tester\WebApplication3
TransientService 1 created
Controller created
Controller disposed
TransientService 1 disposed
TransientService 2 created
Controller created
Controller disposed
TransientService 2 disposed
```

**Comment by AntonioDrusin** [comment] 2020-08-09 13:05
3.1 tester project (results as above) https://github.com/AntonioDrusin/WindsorNetCore31Tester
2.2 tester project https://github.com/AntonioDrusin/WindsorNetCore22Tester (transients are released by castle windsor).

**Comment by generik0** [comment] 2020-08-10 04:47
@ltines as far as i know, Castle should be disposing the transients when the patents are disposed (in this case the controllers, correct?)

Otherwise We get memory leaks.
Do We have a tracking issue here? Ie, items manually / Factory resolved also need to manually released?

**Comment by AntonioDrusin** [comment] 2020-08-10 13:28
Note that this behavior only applies to the controllers. Manually resolving and releasing results in the transient dependencies being correctly released.

**Comment by generik0** [comment] 2020-08-10 15:24
So the controller ends up being single instance for the app lifetime?

Og the controller is Scoped to the request?

Ie i would Think That the correct behaviour for the controllers is a new i stance Per request. Ie scoped. And ctor transients would Then also be scoped at the same time, because there lifetime is related to What created them.


How is the facility doing the controllers?

**Comment by AntonioDrusin** [comment] 2020-08-10 16:50
The controller is released correctly after each web request. The controller depends on a component registered with lifestyle transient. That component is created each time the controller is created, but it does not get released.
The controller is disposed directly by the asp framework.

**Comment by AntonioDrusin** [comment] 2020-08-10 17:13
I am not sure of how this machinery should work. It looks like the controller is disposed by Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker with a call to _cacheEntry.ControllerReleaser(_controllerContext, _instance). But this call does not call Release on Windsor's kernel.
Later the "burden"(?) dependencies are released by Microsoft.AspNetCore.Http.Features.RequestServicesFeature calling dispose on the IServiceScope (that eventually dispose all the dependencies in the burden).

I would have expected the ResourceInvoker derived class (in this case ControllerActionInvoker) to somehow call the Release in Windsor. 

Is it expected that all dependencies for a controller be contained in the ServiceScope including the transient ones?

**Comment by AntonioDrusin** [comment] 2020-08-10 18:05
Getting deeper here. It looks like all the transients are added to the list of burdens (instance2burden) of the same instance of a LifecycledComponentsReleasePolicy. Those burdens are not released when the controller is released.

**Comment by generik0** [comment] 2020-08-10 18:10
I agree with you.
If the controller is disposed / released then ctor injected transients should release.

This sounds like a classic tracking issue.

**Comment by AntonioDrusin** [comment] 2020-08-10 20:23
Note @ltines  suggests to use LifestyleNetTransient to register transient components. I just don't know if that is the best way to to do so as it affects most of our internal library registrations in a way that is "host" dependent.

**Comment by generik0** [comment] 2020-08-11 04:47
@AntonioDrusin yes I read that, and I also agree with you. 
As far as I know, castle disposes / release transients when the parent object is disposed/ released / deconstructed.
Hence, I don't see why there should be a difference.
I hope to be able to look more at this on Thursday/Friday earliest. But I am looking forward to seeing anything you find!!'

**Comment by AntonioDrusin** [comment] 2020-08-14 21:30
@ltines  had to implement it this way.

We are using the custom scope "ExtensionContainerScopeAccessor" + "ExtensionContainerScope" to know when to release the burdens.

.Net core disposes of the controller itself after "resolving" its dependencies. Allowing Windsor to manage the resolution of the controller I think it is not possible to automatically release its dependencies without having a scope.

This is why there is LifestyleNetTransient. It registers the resolved component to the scope that .net core ends after disposing the controller.

At this point, without taking control of the release in .net core, I am not sure how it would be possible to implement this correctly.

**Comment by AntonioDrusin** [comment] 2020-08-14 22:04
The solution was very simple. We had to give windsor control over the creation of the controller.
https://andrewlock.net/controller-activation-and-dependency-injection-in-asp-net-core-mvc/#the-servicebasedcontrolleractivator

Simply calling:
```
            services
                .AddControllers()
                .AddControllersAsServices();
```
fixed my issue.

I think the only thing needed for this issue to go away is to document this extension. I think that the LifestyleNetTransient still has value if you do not want to use windsor to resolve the controller.

**Comment by generik0** [comment] 2020-08-24 07:32
@AntonioDrusin will you update the document for this and make a PR please,.
Great, great find!!!

**Comment by AntonioDrusin** [comment] 2020-08-25 20:17
I was thinking the same, I just did not find a good way to override all transients to be registered as LifestyleTransient. But calling AddControllerAsServices fixes it for me. I think that should fix other issues, for example lazy injections and lambda injections into the controller. I prefer to use all of the capabilities of Windsor when constructing a controller.

**Comment by generik0** [comment] 2020-09-24 09:23
@AntonioDrusin did you have time to document the AddControllersAsServices in the md?
If so, i think we should close.

**Comment by ltines** [comment] 2020-10-05 19:12
Sorry for being bit MIA.

`AddControllerAsServices` would definitely fix it or we can add an option to `UseWindsorContainerServiceProvider` to tie instances of Transient services to `scopeCache` of current scope. That will make sure it will behave same as `IServiceCollection.AddTransient` and ppl can decide how they want it to behave and keep the behaviour in sync for both service definitions.

Thoughts?

**Comment by generik0** [comment] 2020-10-06 05:15
@ltines welcome back :-)
I Think it would be good to add options for both, so both Can be handles within the facility...

**Comment by generik0** [comment] 2020-11-11 07:52
@AntonioDrusin @ltines should we leave it as the AddControllerAsServices documentation?

**Comment by robertcoltheart** [comment] 2020-11-12 00:54
Can we close this issue and release 5.1.0?

**Comment by rmszc81** [comment] 2020-11-12 02:16
@robertcoltheart got here by accident, needed to check this situation and it's working well. I can't wait for v5.1, :D

**Comment by generik0** [comment] 2020-11-13 13:32
@AntonioDrusin can we close please :)

**Closed** 2020-11-13 13:43 UTC
