### ISSUE TITLE
WcfIntegration: System.TypeLoadException occurred in mscorlib.dll

### ISSUE THREAD

**Issue by michal6** [castleproject/Windsor#69] opened 2014-09-10 08:53 UTC
I use Windsor together with WCF and I'm getting this exception in Visual Studio 2013 (2012 is fine):

```
System.TypeLoadException occurred
  _HResult=-2146233054
  _message=GenericArguments[0], 'System.ServiceModel.ServiceHostBase', on 
           'Castle.Facilities.WcfIntegration.IChannelFactoryBuilder`1[M]' 
           violates the constraint of type parameter 'M'.
  HResult=-2146233054
  IsTransient=false
  Message=GenericArguments[0], 'System.ServiceModel.ServiceHostBase', on 
          'Castle.Facilities.WcfIntegration.IChannelFactoryBuilder`1[M]' 
          violates the constraint of type parameter 'M'.
  ResourceId=0
  TypeName=""
  InnerException: 
```

I use WCFFacility and I start WCF host by

```
host = new DefaultServiceHostFactory().CreateServiceHost(typeof(IAdminServices).AssemblyQualifiedName, new Uri[0]);
host.Open();
```

In Windows Forms application (self hosted service). In IIS svc service I use

```
<%@ ServiceHost
  Language="C#" Service="MyService"
  Factory="Castle.Facilities.WcfIntegration.DefaultServiceHostFactory, Castle.Facilities.WcfIntegration"
  %>
```

Problem appears in both cases. I use version 3.3.0 of the library.

**Comment by jonorossi** [comment] 2015-01-02 04:42
@michal6 @alahijani could either of you provide a working repro as a VS project that works in 2012 and fails in 2013, it would make it much easier to track down the issue. Does the demo project (https://github.com/castleproject/Windsor/tree/master/src/Castle.Facilities.WcfIntegration.Demo) in our repository reproduce the problem?

P.S. Once this issue is resolved remember to update http://stackoverflow.com/questions/25182463/castle-windsor-wcf-and-system-typeloadexception-occurred-in-mscorlib-dll which @michal6 has created.

**Comment by michal6** [comment] 2015-01-02 08:39
@jonorossi you can find VS project to reproduce the issue here:

https://github.com/michal6/castle-wcf-System.TypeLoadException

**Comment by jonorossi** [comment] 2015-01-02 10:26
Thanks @michal6, I just tried it on VS2013 and it works for me, it gets to the `Console.ReadKey()` line.

I'm running:
* Visual Studio Ultimate 2013 Version 12.0.30110.00 Update 1
* .NET Framework 4.5.51641 (according to the VS about dialog)
* Castle.Core 3.3.3
* Castle.Windsor 3.3.0
* Castle.WcfIntegrationFacility 3.3.0

**Comment by michal6** [comment] 2015-01-02 10:30
@alahijani Do you have "Break when exception is thrown" checked in debug settings?

**Comment by jonorossi** [comment] 2015-01-02 11:14
@michal6 ah yes, turned of "Just My Code" and breaking on all CLR exceptions ticked reproduces it.

**Comment by jonorossi** [comment] 2015-01-02 12:13
OK, we've got a `catch` block in Windsor to gracefully handle this undocumented exception thrown by `Type.MakeGenericType` under specific circumstances. Unfortunately we don't know why it sometimes gets thrown according to Krzysztof's comment, and since it is thrown in unmanaged code we won't be able to find out. There is some indication that the debugger might be causing it. By catching all exceptions with "Just My Code" turned off you'll pick it up. Microsoft has also got a `catch` block for this in the .NET Framework code, but they then rethrow it.

* [Windsor's code calling Type.MakeGenericType](https://github.com/castleproject/Windsor/blob/master/src/Castle.Windsor/Core/Internal/TypeUtil.cs#L85)
* [Type.MakeGenericType in the reference source](http://referencesource.microsoft.com/#mscorlib/system/rttype.cs,4280)

Do you have "Just My Code" enabled or disabled in VS2012? I don't have VS2012 installed to test, but if you've got it enabled that would explain the difference between VS2012 and VS2013.

**Comment by michal6** [comment] 2015-01-02 13:07
Yeah I have it enabled in VS 2012. So it work in the same way in both Visual Studios. Thanks for explanation @jonorossi.

**Comment by jonorossi** [comment] 2015-01-02 14:10
@michal6 unfortunately since there is no fix we can make (unless we wanted to write our own generic constraint processing which isn't simple) I'm going to close this issue, and we'll just have to continue working around this .NET Framework defect.

**Closed by jonorossi** 2015-01-02 14:10 UTC

**Comment by alahijani** [comment] 2015-01-03 04:38
Thanks Jonathon for the update. We discovered that the real issue with our code was actually unrelated to this exception. For some reason, the actual error was being suppressed, and since this was the only exception that was being thrown it became our main suspect.
