### ISSUE TITLE
AspNet Core 3.1 An item with the same key has already been added

### ISSUE THREAD

**Issue by chrisheil** [castleproject/Windsor#559] opened 2020-11-11 20:46 UTC
I am experiencing an issue similar to issue #533 while running the Castle.Windsor.Extensions.DependencyInjection v5.1.0-beta001 package. This is only occurring only on startup under load, and seem to be resolved on subsequent requests.

This is the stack trace I am getting from the error

```
System.ArgumentException: An item with the same key has already been added. Key: ModelBinderFactory / IModelBinderFactory
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Castle.MicroKernel.Lifestyle.Scoped.ScopeCache.set_Item(Object id, Burden value)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.TryResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency, Object& value)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>n__0(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.TryResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency, Object& value)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>n__0(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.TryResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency, Object& value)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>n__0(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.ResolveAll(Type service, Arguments arguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.ResolveAll(Type service, Arguments arguments)
   at Castle.MicroKernel.Resolvers.SpecializedResolvers.CollectionResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.Windsor.Extensions.DependencyInjection.Resolvers.RegisteredCollectionResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.TryResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency, Object& value)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>n__0(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.WindsorContainer.Resolve(Type service)
   at Castle.Windsor.Extensions.DependencyInjection.WindsorScopedServiceProvider.ResolveInstanceOrNull(Type serviceType, Boolean isOptional)
   at Castle.Windsor.Extensions.DependencyInjection.WindsorScopedServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Here is how I am registering Castle Windsor

```
public void ConfigureContainer(IWindsorContainer container)
{
    container.Kernel.Resolver.AddSubResolver(new CollectionResolver(container.Kernel, true));
    container.AddFacility<TypedFactoryFacility>();
    var location = AppContext.BaseDirectory;
    container.Install(
        FromAssembly.InDirectory(
            new AssemblyFilter(location)
                .FilterByName(a => a.Name.StartsWith("MyProject"))
            )
    );
}
```

For my service registrations I am using `IWindsorInstaller`, and `.LifeStyle.ScopedToNetServiceScope()` when I want a per-web-request lifestyle

**Comment by stylefish** [comment] 2020-11-12 16:25
we copied this code to give it a try and make some adjustments and tests for getting a better net core experience.
we faced the same issue and ending up exchanging the ScopeCache with a self implemented `ConcurrentScopeCache`. the code is as follows:

```
internal class ExtensionContainerScope : ILifetimeScope
	{
		public static ExtensionContainerScope Current => current.Value;
		public static string TransientMarker = "Transient";
		
        protected static readonly AsyncLocal<ExtensionContainerScope> current = new AsyncLocal<ExtensionContainerScope>();
		
        private readonly ExtensionContainerScope parent;
		private readonly IScopeCache scopeCache;
	   
		protected ExtensionContainerScope(ExtensionContainerScope parent)
        {
            scopeCache = new ConcurrentScopeCache();
            this.parent = parent ?? ExtensionContainerRootScope.RootScope;
        }

		public static ExtensionContainerScope BeginScope(ExtensionContainerScope parent)
		{
			var scope = new ExtensionContainerScope(parent);
			current.Value = scope;
			return scope;
		}


		public void Dispose()
		{
            if (scopeCache is IDisposable disposableCache)
			{
				disposableCache.Dispose();
			}

			current.Value = parent;
		}

		public Burden GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
		{
			if(model.Configuration.Attributes.Get(TransientMarker) == Boolean.TrueString )
			{
				var burden = createInstance(_ => {});
				scopeCache[burden] = burden;
				return burden;
			}
			else
			{
				var burden = scopeCache[model];
				if (burden is null)
				{
					scopeCache[model] = burden = createInstance(_ => {});
				}

				return burden;
			}
		}

		/// <summary>
		/// Forces a specific <see name="ExtensionContainerScope" /> for 'using' block. In .NET scope is tied to an instance of <see name="System.IServiceProvider" /> not a thread or async context
		/// </summary>
		internal class ForcedScope : IDisposable
		{
			private readonly ExtensionContainerScope previousScope;
			public ForcedScope(ExtensionContainerScope scope)
			{
				previousScope = ExtensionContainerScope.Current;
				ExtensionContainerScope.current.Value = scope;
			}
			public void Dispose()
			{
				ExtensionContainerScope.current.Value = previousScope;
			}
		}
	}
```

if i find the time to think me into it again i could create a PR, or maybe someone could with this code. 
from our experience this seems safe :) feel free to use/integrate it or modify it. we are glad when we can use the release 5.1.0 of windsor and dump our test code ;)
greetings + thanks for the work :)

**Comment by jonorossi** [comment] 2020-11-13 02:42
> I am experiencing an issue similar to issue #533 while running the Castle.Windsor.Extensions.DependencyInjection v5.1.0-beta001 package

From a brief look this appears to be the same as #533, not similar.

**Comment by generik0** [comment] 2020-11-13 13:28
Hi.
I am confused. Do we have an issue?
@chrisheil can you make a small demo project with the issue?

**Comment by stylefish** [comment] 2020-11-13 14:11
@generik0 i cannot say safely because we're using the class i mentioned above, at the moment i do not have the time to make a sample or unit test project, maybe next week, but in the code file 
https://github.com/castleproject/Windsor/blob/35ebd6e5a77de289536b3862f366d6cbfad19ecc/src/Castle.Windsor/MicroKernel/Lifestyle/Scoped/ScopeCache.cs#L26
there is a comment that indicates that this might still be an issue.
like i said we changed some things with our copy of the code and this specific class `ConcurrentScopeCache` did not make any problems in our tests and deployments of the code.
if you guys have the time to wait i'll try to make a test case / sample to reproduce this and will thest with the current pre release nuget packages if the error is still present, but i sadly dont have that time right now... 

greetings

**Comment by generik0** [comment] 2020-11-13 14:23
Hi @stylefish
I committed a lock on the scope caching for the Netcore integration a while ago. The issue should be fixed.

I thought @jonorossi triggered a build with these changes.

Please, yes, make a demo of your specific issue next week, and I will also check your issue against the current implementation.

You don't need to make the demo complex, just a app that starts up with the exceptions.

I have time next week to help..

**Comment by stylefish** [comment] 2020-11-13 16:33
Hi @generik0 
i saw that, i think the issue will be fixed by your PR, we did basically the same but did it in the scope cache class, not in the "ExtensionContainerScope".
i just thought when this issue gets posted again maybe its not fixed (or the nuget packages are not up to date?).
anyhow: i will try it with our complete project, happened there every start. 
i will use the current nuget prerelease packages and report back when i find the time.
thanks :)

**Comment by chrisheil** [comment] 2020-11-13 17:12
@generik0 Here is a [test project](https://github.com/chrisheil/WindsorStartupError) I created for this. I am starting the asp.net site using a console, then running the test runner to hit it 100 times in a row to reproduce the error

I may just not understand the release process and this could have been fixed already. I saw issue 533 had been resolved and merged into `master` on Sept 15 in commit d3c18a06844c98fd7e98f833c3b782c833323e40, and assumed this beta would have the latest code. Looking at the history for the tag `v5.1.0-beta001` I only see commits through June.

Sorry for the confusion. When will this update be included in the 5.1.0 beta?

**Comment by generik0** [comment] 2020-11-13 17:16
@jonorossi can you trigger a new beta build and Nuget deploy so we can ensure everything = good, and no issue?

**Comment by jonorossi** [comment] 2020-11-15 23:34
@generik0 seems overkill to make a beta2 release, every master build is available in the NuGet preview feed.

**Comment by robertcoltheart** [comment] 2020-11-16 01:27
@chrisheil @generik0 I downloaded the test project and updated to the latest preview release from appveyor, and this issue goes away. So I think its safe to say the issue has already been addressed, and we can close this issue.

**Comment by jonorossi** [comment] 2020-11-16 03:43
Thanks heaps @robertcoltheart. With that known, closing as duplicate.

**Closed by jonorossi** 2020-11-16 03:43 UTC
