### ISSUE TITLE
Extensions.DependencyInjection: "An item with the same key has already been added" exception related to scoped lifestyle

### ISSUE THREAD

**Issue by mdavis** [castleproject/Windsor#533] opened 2020-07-01 20:32 UTC
When using the new Extensions.DependencyInjection package with an ASP.NET Core 3.1 web application, if multiple requests come in as soon as the application starts up, I'm seeing ArgumentExceptions with the message "An item with the same key has already been added." specifying some service with a scoped lifestyle that was being resolved.

Here is an example error log:

```
[2020-07-01 14:51:50.7450] (ERROR) Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key: NoopClaimsTransformation / IClaimsTransformation
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Castle.MicroKernel.Lifestyle.Scoped.ScopeCache.set_Item(Object id, Burden value)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.TryResolveCore(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency, Object& value)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>n__0(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.Windsor.Extensions.DependencyInjection.Scope.ExtensionContainerScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.Handlers.AbstractHandler.Resolve(CreationContext context)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.WindsorContainer.Resolve(Type service)
   at Castle.Windsor.Extensions.DependencyInjection.WindsorScopedServiceProvider.ResolveInstanceOrNull(Type serviceType, Boolean isOptional)
   at Castle.Windsor.Extensions.DependencyInjection.WindsorScopedServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Here is a sample project that reproduces the problem for me.  If I set the Requests constant in the client application to 1, then everything works fine, but setting it higher than that causes exceptions to be thrown.

[SameKeyTest.zip](https://github.com/castleproject/Windsor/files/4860290/SameKeyTest.zip)

**Comment by jonorossi** [comment] 2020-08-31 12:25
@generik0 do you know if this is still a problem after the recent changes?

**Comment by generik0** [comment] 2020-08-31 12:43
@jonorossi i don't know. But I can test and try to diag in the weekend. Thanks for reminding me/us...!

**Comment by minhhut** [comment] 2020-09-08 13:31
I have same issue

**Comment by generik0** [comment] 2020-09-08 17:07
The issue is here. A "burden" already existing in the cache.
![image](https://user-images.githubusercontent.com/2411563/92506436-c4e01700-f205-11ea-892e-8951610db641.png)

Looks like the IActionInvokerFactory is being resolved in scope a scope, and is not completed before the next call. Interesting that a factory should be in a scope and hence a burden,..

**Comment by generik0** [comment] 2020-09-08 17:17
@jonorossi @AntonioDrusin any thoughs. Is a static lock in the WindsorScopedServiceProvider bad?

![image](https://user-images.githubusercontent.com/2411563/92507796-d32f3280-f207-11ea-8fe2-56a3aef4b01c.png)
![image](https://user-images.githubusercontent.com/2411563/92507811-da564080-f207-11ea-866c-d7509729ce28.png)

@minhhut @mdavis thoughts? a fix, or a work around, good/bad practice?

**Comment by AntonioDrusin** [comment] 2020-09-08 19:14
I feel that locking in general is a performance issue. I am downloading the project and looking at it today. I would not disagree with adding the _lock to get the ball rolling for all people blocked by this bug.

**Comment by generik0** [comment] 2020-09-08 19:33
looks like the lock can be added in the  GetCachedInstance. Hence the transients won't be blocked in this case..

![image](https://user-images.githubusercontent.com/2411563/92519838-f1525e00-f21a-11ea-8e3a-f17a36a8d03c.png)

**Comment by generik0** [comment] 2020-09-08 20:06
@jonorossi please add label "Bug" and please check PR #547 :-)

**Comment by minhhut** [comment] 2020-09-08 21:59
I could reproduce this issue by doing load test (multiple requests) after server started. No workaround for now, it just happens at the start, then it's fine

**Comment by generik0** [comment] 2020-09-09 04:52
Yes it happens on startup because this is when MS resolve a number of services. Like the factories and loggers. 
They seam to be doing it multi thread on the same scope (but multiple scopes) and this is causing an issue for castle when creating multiple the instances on the same scope. The creation needs to be thread safe, so We only get 1 instance Per scope.

My PR fixes this.

**Comment by generik0** [comment] 2020-09-13 15:55
@jonorossi improved nestling and improved naming of variables for readability

**Closed** 2020-09-15 09:10 UTC
Labels: bug
