### ISSUE TITLE
IIS Process hangs when recycling due to deadlock happened with Castle Windsor

### ISSUE THREAD

**Issue by ahmedtolba1984** [castleproject/Windsor#578] opened 2020-12-03 21:17 UTC
Dears,
My application is hanging when IIS App Pool Process w3wp.exe got recycled, and after a lot of investigations and taking a lot  of crash dump files, the root cause of my issue was due to **Threads being blocked and a deadlock happened.**
it happened when I changed my cache API from **Transient** to **Singleton**
Here's the stack trace I got when investigating the dump file. 
--
[[HelperMethodFrame]]
System.Threading.SpinWait.SpinOnceCore(Int32)+7d
Castle.Core.Internal.ThreadSafeInit.ExecuteThreadSafeOnce()+9e
Castle.MicroKernel.Lifestyle.SingletonLifestyleManager.Resolve(Castle.MicroKernel.Context.CreationContext, Castle.MicroKernel.IReleasePolicy)+4f
Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(Castle.MicroKernel.Context.CreationContext, Boolean, Boolean, Castle.MicroKernel.Burden ByRef)+14a
Castle.MicroKernel.Handlers.DefaultHandler.Resolve(Castle.MicroKernel.Context.CreationContext, Boolean)+21
Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(Castle.MicroKernel.Context.CreationContext, Castle.Core.ComponentModel, Castle.Core.DependencyModel)+fffffffffb40fe8c
Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernel(Castle.MicroKernel.Context.CreationContext, Castle.Core.ComponentModel, Castle.Core.DependencyModel)+fffffffffb40fd6c
Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(Castle.MicroKernel.Context.CreationContext, Castle.MicroKernel.ISubDependencyResolver, Castle.Core.ComponentModel, Castle.Core.DependencyModel)+fffffffffb40fa76
Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.ObtainPropertyValue(Castle.MicroKernel.Context.CreationContext, Castle.Core.PropertySet, Castle.MicroKernel.IDependencyResolver)+fffffffffb416ab8
Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.SetUpProperties(System.Object, Castle.MicroKernel.Context.CreationContext)+b3
Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(Castle.MicroKernel.Context.CreationContext)+fffffffffb40e968
Please, advice me on how to solve this issue as it happened on Production and affect our customers

![DebugDumpFile](https://user-images.githubusercontent.com/6592222/101097105-45c26b00-35c9-11eb-9061-ef9ae17014f7.PNG)

**Comment by ahmedtolba1984** [comment] 2020-12-03 23:54
@jonorossi  any updates as this issue is critical for us

**Comment by jonorossi** [comment] 2020-12-04 00:17
I'm not trying to sound rude, but I think you misunderstand the open source license you are using Windsor under, you are the one being paid to maintain your system for your customers, not sure what you expect me to do.

For it to be blocked there you've probably got a deadlock, look at more of your threads in the memory dumps and you might find you've got a race from multiple ASP.NET worker threads to initialise the singleton. You've probably introduced a deadlock by making it a singleton because of some other assumptions. I've not seen anyone report anything like this in the decade that code has been there, you'll have to work it out in the code I can't see.

**Comment by jonorossi** [comment] 2020-12-04 09:29
Closing as this has no reproduction, and the stack trace outside of Windsor code and some of the Winsdor frames is completely snipped off, so no idea how you are even initialising your container. If you find a defect we can reopen the issue.

**Closed by jonorossi** 2020-12-04 09:29 UTC
Labels: needs-repro
