### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Mattio91** [castleproject/Windsor#150] opened 2016-09-26 13:26 UTC
Hi, 
Windsor, while resolving, throws exceptions like that:

```
Error details: An error ocurred while executing the step
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Castle.Windsor.Proxy.AbstractProxyFactory.ShouldCreateProxy(ComponentModel model)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstance(CreationContext context, ConstructorCandidate constructor, Object[] arguments)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.SingletonLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at DPF.Common.Step`2.GetRunnerComponents(String jobSettings, String stepSettings) 
```

What leads to function: 

```
        public bool ShouldCreateProxy(ComponentModel model)
        {
            if (model.HasInterceptors)
            {
                return true;
            }

            var options = model.ObtainProxyOptions(false);
            if (options != null && options.RequiresProxy)
            {
                return true;
            }
            if (selectors != null && selectors.Any(s => s.HasInterceptors(model)))
            {
                return true;
            }

            return false;
        }
```

Is it problem in windsor or in my project? Shoundn't it be thread save or something?

**Comment by Beton** [comment] 2016-10-17 14:37
Hey, I've encountered similar issue. Has anyone investigated this?
Thanks

My stack: 

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.CanResolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.ObtainPropertyValue(CreationContext context, PropertySet property, IDependencyResolver resolver)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.SetUpProperties(Object instance, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, IDictionary additionalArguments, IReleasePolicy policy)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
   at yTos.Core.MVC.Controllers.CastleWindsorControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)

**Comment by Mattio91** [comment] 2016-10-18 08:08
Oh, i didn't fix it on my own, but its related with ProxyGenerator class. 
I think you should use it something like new DefaultProxyFactory(_proxyGenerator)

**Comment by neutmute** [comment] 2017-09-27 00:09
I'm wrestling with Castle Windsor and WCF service registration. If I remove a `behavior` with an empty `name` from `serviceBehaviors` then I get this error. 

```
  <behavior name="">
          <serviceMetadata httpGetEnabled="false" httpsGetEnabled="false" />
          <serviceDebug includeExceptionDetailInFaults="true" />
          <dataContractSerializer maxItemsInObjectGraph="2147483647" />
          <serviceThrottling maxConcurrentCalls="1000" maxConcurrentInstances="1000" maxConcurrentSessions="1000" />
        </behavior>
```

**Comment by jonorossi** [comment] 2017-09-27 05:28
@Mattio91 @Beton no one is investigating this issue because we at least need a repro, something we can run that reproduces the exception.

@neutmute your problem might be the same as this defect but you didn't include your stack trace to compare, @Mattio91's makes no mention of WCF anywhere.

We need a repro, however we'd love a pull request with a fix, that'll guarantee this gets fixed for you guys. The pull request doesn't need to be perfect, we can work together once we've got something.

Without a repro we'll close this issue in a few days.

**Comment by jonorossi** [comment] 2017-10-05 17:45
Closing this issue because we don't have a repro.

**Closed by jonorossi** 2017-10-05 17:45 UTC
Labels: needs-repro
